---
homebrew_taps:
  - caskroom/cask
  - homebrew/services
  - sanemat/font

homebrew_packages:
  - { name: automake }
  - { name: boost-python }
  - { name: cmake }
  - { name: cpanminus }
  - { name: ctags }
  - { name: direnv }
  - { name: docker }
  - { name: fontforge }
  - { name: fzf }
  - { name: go }
  - { name: grep }
  - { name: htop }
  - { name: icu4c }
  - { name: imagemagick }
  - { name: jq }
  - { name: libtool }
  - { name: lua }
  - { name: luajit }
  - { name: mas }
  - { name: mysql }
  - { name: neovim }
  - { name: nkf }
  - { name: openssl }
  - { name: peco }
  - { name: pstree }
  - { name: python }
  - { name: python3 }
  - { name: q }
  - { name: reattach-to-user-namespace }
  - { name: ricty }
  - { name: rmtrash }
  - { name: rust }
  - { name: ssh-copy-id }
  - { name: the_silver_searcher }
  - { name: tig }
  - { name: tmux }
  - { name: vim }
  - { name: w3m }
  - { name: wget }
  - { name: zlib }
  - { name: zsh }

homebrew_cask_packages:
  - { name: alfred }
  - { name: appcleaner }
  - { name: caffeine }
  - { name: docker }
  - { name: dropbox }
  - { name: evernote }
  - { name: firefox }
  - { name: google-chrome }
  - { name: google-japanese-ime }
  - { name: growlnotify }
  - { name: iterm2 }
  - { name: karabiner-elements }
  - { name: keyboardcleantool }
  - { name: slack }
  - { name: the-unarchiver }
  - { name: vlc }
  - { name: xquartz }

mas_packages:
  - { name: 1Password, id: 443987910 }
  - { name: Growl, id: 467939042 }
  - { name: Kindle, id: 405399194 }
  - { name: BetterSnapTool, id: 417375580 }
  - { name: Xcode, id: 497799835 }
